# Generated by Django 2.1.1 on 2018-09-23 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dtNascimento', models.DateField()),
                ('rg', models.CharField(max_length=12)),
                ('cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pescoco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('toraxica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('braco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anteBraco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abdominal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coxaEsquerda1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coxaEsquerda2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coxaEsquerda3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coxaDireita1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coxaDireita2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coxaDireita3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pantuEsq', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pantuDir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alunoRelacionado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
    ]
